Cherry pick of 8b5c880195576a5013860fa6e37424d75dc9426b failed
stdout:
CONFLICT (modify/delete): portal_timesheet/security/portal_timesheet.xml deleted in HEAD and modified in 8b5c880... [FIX] portal_timesheet: fix access of internal users. Version 8b5c880... [FIX] portal_timesheet: fix access of internal users of portal_timesheet/security/portal_timesheet.xml left in tree.
CONFLICT (modify/delete): portal_timesheet/__manifest__.py deleted in HEAD and modified in 8b5c880... [FIX] portal_timesheet: fix access of internal users. Version 8b5c880... [FIX] portal_timesheet: fix access of internal users of portal_timesheet/__manifest__.py left in tree.

stderr:
18:17:45.954621 git.c:439               trace: built-in: git cherry-pick 8b5c880195576a5013860fa6e37424d75dc9426b
error: could not apply 8b5c880... [FIX] portal_timesheet: fix access of internal users
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: